/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef DataSinks_TYPES_H
#define DataSinks_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>
#include "Exprs_types.h"
#include "Types_types.h"
#include "Descriptors_types.h"
#include "Partitions_types.h"


namespace palo {

struct TDataSinkType {
  enum type {
    DATA_STREAM_SINK = 0,
    RESULT_SINK = 1,
    DATA_SPLIT_SINK = 2,
    MYSQL_TABLE_SINK = 3,
    EXPORT_SINK = 4
  };
};

extern const std::map<int, const char*> _TDataSinkType_VALUES_TO_NAMES;

class TDataStreamSink;

class TResultSink;

class TMysqlTableSink;

class TRollupSchema;

class TDataSplitSink;

class TExportSink;

class TDataSink;

typedef struct _TDataStreamSink__isset {
  _TDataStreamSink__isset() : ignore_not_found(false) {}
  bool ignore_not_found :1;
} _TDataStreamSink__isset;

class TDataStreamSink {
 public:

  TDataStreamSink(const TDataStreamSink&);
  TDataStreamSink& operator=(const TDataStreamSink&);
  TDataStreamSink() : dest_node_id(0), ignore_not_found(0) {
  }

  virtual ~TDataStreamSink() throw();
   ::palo::TPlanNodeId dest_node_id;
   ::palo::TDataPartition output_partition;
  bool ignore_not_found;

  _TDataStreamSink__isset __isset;

  void __set_dest_node_id(const  ::palo::TPlanNodeId val);

  void __set_output_partition(const  ::palo::TDataPartition& val);

  void __set_ignore_not_found(const bool val);

  bool operator == (const TDataStreamSink & rhs) const
  {
    if (!(dest_node_id == rhs.dest_node_id))
      return false;
    if (!(output_partition == rhs.output_partition))
      return false;
    if (__isset.ignore_not_found != rhs.__isset.ignore_not_found)
      return false;
    else if (__isset.ignore_not_found && !(ignore_not_found == rhs.ignore_not_found))
      return false;
    return true;
  }
  bool operator != (const TDataStreamSink &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TDataStreamSink & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TDataStreamSink &a, TDataStreamSink &b);

inline std::ostream& operator<<(std::ostream& out, const TDataStreamSink& obj)
{
  obj.printTo(out);
  return out;
}


class TResultSink {
 public:

  TResultSink(const TResultSink&);
  TResultSink& operator=(const TResultSink&);
  TResultSink() {
  }

  virtual ~TResultSink() throw();

  bool operator == (const TResultSink & /* rhs */) const
  {
    return true;
  }
  bool operator != (const TResultSink &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TResultSink & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TResultSink &a, TResultSink &b);

inline std::ostream& operator<<(std::ostream& out, const TResultSink& obj)
{
  obj.printTo(out);
  return out;
}


class TMysqlTableSink {
 public:

  TMysqlTableSink(const TMysqlTableSink&);
  TMysqlTableSink& operator=(const TMysqlTableSink&);
  TMysqlTableSink() : host(), port(0), user(), passwd(), db(), table() {
  }

  virtual ~TMysqlTableSink() throw();
  std::string host;
  int32_t port;
  std::string user;
  std::string passwd;
  std::string db;
  std::string table;

  void __set_host(const std::string& val);

  void __set_port(const int32_t val);

  void __set_user(const std::string& val);

  void __set_passwd(const std::string& val);

  void __set_db(const std::string& val);

  void __set_table(const std::string& val);

  bool operator == (const TMysqlTableSink & rhs) const
  {
    if (!(host == rhs.host))
      return false;
    if (!(port == rhs.port))
      return false;
    if (!(user == rhs.user))
      return false;
    if (!(passwd == rhs.passwd))
      return false;
    if (!(db == rhs.db))
      return false;
    if (!(table == rhs.table))
      return false;
    return true;
  }
  bool operator != (const TMysqlTableSink &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TMysqlTableSink & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TMysqlTableSink &a, TMysqlTableSink &b);

inline std::ostream& operator<<(std::ostream& out, const TMysqlTableSink& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TRollupSchema__isset {
  _TRollupSchema__isset() : keys_type(false) {}
  bool keys_type :1;
} _TRollupSchema__isset;

class TRollupSchema {
 public:

  TRollupSchema(const TRollupSchema&);
  TRollupSchema& operator=(const TRollupSchema&);
  TRollupSchema() : keys_type() {
  }

  virtual ~TRollupSchema() throw();
  std::vector< ::palo::TExpr>  keys;
  std::vector< ::palo::TExpr>  values;
  std::vector< ::palo::TAggregationType::type>  value_ops;
  std::string keys_type;

  _TRollupSchema__isset __isset;

  void __set_keys(const std::vector< ::palo::TExpr> & val);

  void __set_values(const std::vector< ::palo::TExpr> & val);

  void __set_value_ops(const std::vector< ::palo::TAggregationType::type> & val);

  void __set_keys_type(const std::string& val);

  bool operator == (const TRollupSchema & rhs) const
  {
    if (!(keys == rhs.keys))
      return false;
    if (!(values == rhs.values))
      return false;
    if (!(value_ops == rhs.value_ops))
      return false;
    if (__isset.keys_type != rhs.__isset.keys_type)
      return false;
    else if (__isset.keys_type && !(keys_type == rhs.keys_type))
      return false;
    return true;
  }
  bool operator != (const TRollupSchema &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TRollupSchema & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TRollupSchema &a, TRollupSchema &b);

inline std::ostream& operator<<(std::ostream& out, const TRollupSchema& obj)
{
  obj.printTo(out);
  return out;
}


class TDataSplitSink {
 public:

  TDataSplitSink(const TDataSplitSink&);
  TDataSplitSink& operator=(const TDataSplitSink&);
  TDataSplitSink() {
  }

  virtual ~TDataSplitSink() throw();
  std::vector< ::palo::TExpr>  partition_exprs;
  std::vector< ::palo::TRangePartition>  partition_infos;
  std::map<std::string, TRollupSchema>  rollup_schemas;

  void __set_partition_exprs(const std::vector< ::palo::TExpr> & val);

  void __set_partition_infos(const std::vector< ::palo::TRangePartition> & val);

  void __set_rollup_schemas(const std::map<std::string, TRollupSchema> & val);

  bool operator == (const TDataSplitSink & rhs) const
  {
    if (!(partition_exprs == rhs.partition_exprs))
      return false;
    if (!(partition_infos == rhs.partition_infos))
      return false;
    if (!(rollup_schemas == rhs.rollup_schemas))
      return false;
    return true;
  }
  bool operator != (const TDataSplitSink &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TDataSplitSink & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TDataSplitSink &a, TDataSplitSink &b);

inline std::ostream& operator<<(std::ostream& out, const TDataSplitSink& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TExportSink__isset {
  _TExportSink__isset() : broker_addresses(false), properties(false) {}
  bool broker_addresses :1;
  bool properties :1;
} _TExportSink__isset;

class TExportSink {
 public:

  TExportSink(const TExportSink&);
  TExportSink& operator=(const TExportSink&);
  TExportSink() : file_type(( ::palo::TFileType::type)0), export_path(), column_separator(), line_delimiter() {
  }

  virtual ~TExportSink() throw();
   ::palo::TFileType::type file_type;
  std::string export_path;
  std::string column_separator;
  std::string line_delimiter;
  std::vector< ::palo::TNetworkAddress>  broker_addresses;
  std::map<std::string, std::string>  properties;

  _TExportSink__isset __isset;

  void __set_file_type(const  ::palo::TFileType::type val);

  void __set_export_path(const std::string& val);

  void __set_column_separator(const std::string& val);

  void __set_line_delimiter(const std::string& val);

  void __set_broker_addresses(const std::vector< ::palo::TNetworkAddress> & val);

  void __set_properties(const std::map<std::string, std::string> & val);

  bool operator == (const TExportSink & rhs) const
  {
    if (!(file_type == rhs.file_type))
      return false;
    if (!(export_path == rhs.export_path))
      return false;
    if (!(column_separator == rhs.column_separator))
      return false;
    if (!(line_delimiter == rhs.line_delimiter))
      return false;
    if (__isset.broker_addresses != rhs.__isset.broker_addresses)
      return false;
    else if (__isset.broker_addresses && !(broker_addresses == rhs.broker_addresses))
      return false;
    if (__isset.properties != rhs.__isset.properties)
      return false;
    else if (__isset.properties && !(properties == rhs.properties))
      return false;
    return true;
  }
  bool operator != (const TExportSink &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TExportSink & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TExportSink &a, TExportSink &b);

inline std::ostream& operator<<(std::ostream& out, const TExportSink& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _TDataSink__isset {
  _TDataSink__isset() : stream_sink(false), result_sink(false), split_sink(false), mysql_table_sink(false), export_sink(false) {}
  bool stream_sink :1;
  bool result_sink :1;
  bool split_sink :1;
  bool mysql_table_sink :1;
  bool export_sink :1;
} _TDataSink__isset;

class TDataSink {
 public:

  TDataSink(const TDataSink&);
  TDataSink& operator=(const TDataSink&);
  TDataSink() : type((TDataSinkType::type)0) {
  }

  virtual ~TDataSink() throw();
  TDataSinkType::type type;
  TDataStreamSink stream_sink;
  TResultSink result_sink;
  TDataSplitSink split_sink;
  TMysqlTableSink mysql_table_sink;
  TExportSink export_sink;

  _TDataSink__isset __isset;

  void __set_type(const TDataSinkType::type val);

  void __set_stream_sink(const TDataStreamSink& val);

  void __set_result_sink(const TResultSink& val);

  void __set_split_sink(const TDataSplitSink& val);

  void __set_mysql_table_sink(const TMysqlTableSink& val);

  void __set_export_sink(const TExportSink& val);

  bool operator == (const TDataSink & rhs) const
  {
    if (!(type == rhs.type))
      return false;
    if (__isset.stream_sink != rhs.__isset.stream_sink)
      return false;
    else if (__isset.stream_sink && !(stream_sink == rhs.stream_sink))
      return false;
    if (__isset.result_sink != rhs.__isset.result_sink)
      return false;
    else if (__isset.result_sink && !(result_sink == rhs.result_sink))
      return false;
    if (__isset.split_sink != rhs.__isset.split_sink)
      return false;
    else if (__isset.split_sink && !(split_sink == rhs.split_sink))
      return false;
    if (__isset.mysql_table_sink != rhs.__isset.mysql_table_sink)
      return false;
    else if (__isset.mysql_table_sink && !(mysql_table_sink == rhs.mysql_table_sink))
      return false;
    if (__isset.export_sink != rhs.__isset.export_sink)
      return false;
    else if (__isset.export_sink && !(export_sink == rhs.export_sink))
      return false;
    return true;
  }
  bool operator != (const TDataSink &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TDataSink & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TDataSink &a, TDataSink &b);

inline std::ostream& operator<<(std::ostream& out, const TDataSink& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
