/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Ddl_CONSTANTS_H
#define Ddl_CONSTANTS_H

#include "Ddl_types.h"

namespace palo {

class DdlConstants {
 public:
  DdlConstants();

};

extern const DdlConstants g_Ddl_constants;

} // namespace

#endif
