/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Ddl_constants.h"

namespace palo {

const DdlConstants g_Ddl_constants;

DdlConstants::DdlConstants() {
}

} // namespace

