/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef HeartbeatService_CONSTANTS_H
#define HeartbeatService_CONSTANTS_H

#include "HeartbeatService_types.h"

namespace palo {

class HeartbeatServiceConstants {
 public:
  HeartbeatServiceConstants();

};

extern const HeartbeatServiceConstants g_HeartbeatService_constants;

} // namespace

#endif
