/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "HeartbeatService_constants.h"

namespace palo {

const HeartbeatServiceConstants g_HeartbeatService_constants;

HeartbeatServiceConstants::HeartbeatServiceConstants() {
}

} // namespace

