/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MetricDefs_CONSTANTS_H
#define MetricDefs_CONSTANTS_H

#include "MetricDefs_types.h"

namespace palo {

class MetricDefsConstants {
 public:
  MetricDefsConstants();

  std::map<std::string, TMetricDef>  TMetricDefs;
};

extern const MetricDefsConstants g_MetricDefs_constants;

} // namespace

#endif
